# Generated by Django 4.1.5 on 2023-01-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eVote_app', '0002_town_citizen_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('starton', models.DateTimeField()),
                ('endson', models.DateTimeField()),
            ],
        ),
    ]
