# Generated by Django 4.1.5 on 2023-01-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eVote_app', '0003_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='choice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='citizenvoted', to='eVote_app.choices'),
            preserve_default=False,
        ),
    ]
