# Generated by Django 4.1.5 on 2023-01-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eVote_app', '0004_citizen_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='choice',
        ),
    ]
