# Generated by Django 4.1.5 on 2023-01-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eVote_app', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
