# Generated by Django 4.1.5 on 2023-01-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eVote_app', '0007_choices_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='active',
        ),
    ]
