# Generated by Django 4.1.5 on 2023-01-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eVote_app', '0009_politicalelection_politicalparty_remove_citizen_town_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicalparty',
            name='politicanelection',
        ),
    ]
