# Generated by Django 4.1.5 on 2023-01-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eVote_app', '0012_alter_application_politicalelection'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalparty',
            name='politicanelections',
            field=models.ManyToManyField(related_name='choices', to='eVote_app.politicalelection'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
