# Generated by Django 4.1.5 on 2023-01-22 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eVote_app', '0014_citizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteelection', to='eVote_app.politicalelection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
