# Generated by Django 4.1.5 on 2023-01-22 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eVote_app', '0015_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='politicalparty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='partyvotes', to='eVote_app.politicalparty'),
            preserve_default=False,
        ),
    ]
