# Generated by Django 4.1.5 on 2023-01-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eVote_app', '0016_vote_politicalparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='uniquenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
